### ISSUE TITLE
Outdated dependencies

### ISSUE THREAD

**Issue by vguzev** [shantanuraj/react-d3-typescript#1]
First of all, thanks for this sample! )
Just want to mention that there are a lot of breaking changes in new version of d3...
See https://github.com/d3/d3/blob/master/CHANGES.md#changes-in-d3-40
It would be great if someone could update this sample to stay up to date.

**Comment by shantanuraj** [comment]
Thanks for this, I've been wanting to update this to the latest APIs.

Mostly fixed with f2f918e and 89c8998
I updated all the other libs in the process as well (react, typescript, webpack)

The only thing I couldn't get to port in the process was the drag functionality
Removed here https://github.com/shantanuraj/react-d3-typescript/commit/d3a9611a03f51e246469f7efac9ab11d950dc992#diff-46ef2374da6211486f3a408db68b2bcbL52

I'll come around and fix that when I get the time.
